"""Emit docs/NUMBERS.md — every citable number, read from the artifacts.

NB: this file must NOT be called numbers.py — that shadows the stdlib
`numbers` module, which numpy imports during its own initialisation, and the
result is an unhelpful circular-import error from deep inside pandas.

Exists so no figure caption or sentence in the write-up is typed from memory. Each row
names the file it came from, so any number in the doc can be traced back in one step.
Regenerate after any re-run:

    python scripts/reference_sheet.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src import behavior, config  # noqa: E402

REAL = ["qwen3.5-9b", "phi-4", "olmo-3-7b-instruct"]
OUT = config.ROOT / "docs" / "NUMBERS.md"


def _j(p: Path):
    return json.loads(p.read_text()) if p.exists() else {}


def main() -> None:
    L: list[str] = ["# Citable numbers", "",
                    "Generated by `scripts/reference_sheet.py` from the artifacts — not typed by "
                    "hand. Every row names its source file. Regenerate after any re-run.",
                    ""]

    # provenance
    L += ["## Run provenance", "", "| model | HF id | rows | cells | statements | dtype | layers | git |",
          "|---|---|---|---|---|---|---|---|"]
    for m in REAL:
        r = _j(config.results_dir(m) / "run_meta.json")
        t = _j(config.results_dir(m) / "truth_axis_meta.json")
        if not r:
            continue
        L.append(f"| `{m}` | `{r.get('model_hf_id')}` | {r.get('manifest_rows')} | "
                 f"{r.get('manifest_cells')} | {r.get('n_statements')} | "
                 f"{r.get('dtype')} (4bit={r.get('load_in_4bit')}) | "
                 f"best={t.get('best_layer')} of {r.get('layer_fractions')} | "
                 f"`{r.get('git_sha')}` |")
    L += ["", "Source: `results/<model>/run_meta.json`, `truth_axis_meta.json`.", ""]

    # headline: row-level
    L += ["## Row-level detectability by confidence (THE replicating result)", "",
          "One probe trained across all cells; AUROC within strata of the model's "
          "confidence in the proposition. `belief` = label from the TRUE/FALSE logit "
          "margin; `groundtruth` = label from ground truth, which touches neither "
          "`d_truth` nor the margin.", "",
          "| model | label | <0.3 | 0.3–0.6 | >0.6 | noise-injection predicts | observed <0.3 |",
          "|---|---|---|---|---|---|---|"]
    for m in REAL:
        d = _j(config.results_dir(m) / "rowlevel.json")
        st = d.get("stratified_auroc", {})
        inj = d.get("noise_injection_control") or {}
        for lab in ("belief", "groundtruth"):
            if lab not in st:
                continue
            def c(k):
                v = st[lab].get(k)
                return (f"**{v['auroc']:.3f}** [{v['ci_lo']:.3f}, {v['ci_hi']:.3f}] "
                        f"n={v['n']}") if v else "—"
            ni = (f"{inj['auroc_after_injecting_noise']:.3f}"
                  if lab == "belief" and inj.get("auroc_after_injecting_noise") else "—")
            ob = (f"{inj.get('observed_low_stratum_auroc'):.3f}"
                  if lab == "belief" and inj.get("observed_low_stratum_auroc") else "—")
            L.append(f"| `{m}` | {lab} | {c('<0.3')} | {c('0.3-0.6')} | {c('>0.6')} | {ni} | {ob} |")
    L += ["", "Noise injection corrupts the CLEAN high-confidence stratum at the "
          "disagreement rate measured in the low stratum. It **undershoots** the observed "
          "value in every model, so label noise does not explain the gradient.", "",
          "Source: `results/<model>/rowlevel.json`.", ""]

    # prompt site
    pr = _j(config.results_dir("qwen3.5-9b") / "rowlevel_prompt.json")
    rs = _j(config.results_dir("qwen3.5-9b") / "rowlevel.json")
    if pr and rs:
        L += ["## Prompt-site control (probe reads before the verdict exists)", "",
              "| label | stratum | response-site | prompt-site |", "|---|---|---|---|"]
        for lab in ("belief", "groundtruth"):
            for k in ("all", "<0.3", "0.3-0.6", ">0.6"):
                a = rs["stratified_auroc"].get(lab, {}).get(k)
                b = pr["stratified_auroc"].get(lab, {}).get(k)
                if a and b:
                    L.append(f"| {lab} | {k} | {a['auroc']:.3f} | {b['auroc']:.3f} |")
        L += ["", "Source: `results/qwen3.5-9b/rowlevel.json` and `rowlevel_prompt.json`.", ""]

    # variance decomposition
    L += ["## Variance decomposition (does NOT replicate — Olmo inverts)", "",
          "| model | n cells | n pairs | target R² | source R² | scenario R² | off-diag AUROC |",
          "|---|---|---|---|---|---|---|"]
    for m in REAL + ["qwen2.5-7b-instruct-dry"]:
        p = config.results_dir(m) / "transfer_long.csv"
        if not p.exists():
            continue
        d = behavior.load_transfer_long(p)
        off = d[~d.is_diag].dropna(subset=["auroc"])
        if len(off) < 10:
            continue
        y = off.auroc.to_numpy()

        def r2(cols):
            X = pd.get_dummies(off[cols].astype(str), drop_first=True).to_numpy(float)
            X = np.column_stack([np.ones(len(y)), X])
            b, *_ = np.linalg.lstsq(X, y, rcond=None)
            r = y - X @ b
            return float(1 - r @ r / ((y - y.mean()) ** 2).sum())
        L.append(f"| `{m}` | {off.source_cell.nunique()} | {len(off)} | "
                 f"**{r2(['target_cell']):.3f}** | **{r2(['source_cell']):.3f}** | "
                 f"{r2(['scenario_source','scenario_target']):.3f} | {y.mean():.3f} |")
    L += ["", "Source: recomputed from `results/<model>/transfer_long.csv`.", ""]

    # horse race
    L += ["## H1 horse race (pre-registered primary — not supported)", "",
          "| model | R² M0 scenario | R² M2 both | ΔR² | within-scenario perm p | n pairs |",
          "|---|---|---|---|---|---|"]
    for m in REAL:
        h = _j(config.results_dir(m) / "baselines.json").get("horse_race", {})
        if not h:
            continue
        L.append(f"| `{m}` | {h['r2_scenario_only_M0']:.3f} | {h['r2_both_M2']:.3f} | "
                 f"{h['delta_r2_M2_vs_M0']:.3f} | **{h['perm_p_within_scenario']:.3f}** | "
                 f"{h['n_pairs']} |")
    L += ["", "The permutation test is the only calibrated one of the three; the naive F "
          "and cluster-on-source have ~74–76% type-I error on this design and should not "
          "be quoted.", "", "Source: `results/<model>/baselines.json`.", ""]

    # baselines
    L += ["## Baselines", "",
          "| model | probe in-dist | within-class OOD | style-shift | text-only | length-only | random floor |",
          "|---|---|---|---|---|---|---|"]
    for m in REAL:
        b = _j(config.results_dir(m) / "baselines.json")
        if not b:
            continue
        f = lambda k: f"{b[k]:.3f}" if isinstance(b.get(k), (int, float)) else "—"  # noqa: E731
        L.append(f"| `{m}` | {f('in_dist_diag_auroc')} | {f('within_class_ood_auroc')} | "
                 f"{f('style_shift_auroc')} | {f('behavioral_text_auroc')} | "
                 f"{f('length_only_auroc')} | {f('random_direction_floor')} |")
    L += ["", "Source: `results/<model>/baselines.json`.", ""]

    # compliance / refusal
    L += ["## Compliance and refusal by cell group", ""]
    for m in REAL:
        p = config.results_dir(m) / "compliance.csv"
        if not p.exists():
            continue
        L += [f"**`{m}`**", "", "```", pd.read_csv(p).to_string(index=False), "```", ""]
    L += ["Source: `results/<model>/compliance.csv`.", ""]

    # instrument
    L += ["## Instrument: d_truth vs the independent belief measure", "",
          "| model | truth AUROC | sign agreement | d_truth acc | margin acc | label disagreement |",
          "|---|---|---|---|---|---|"]
    for m in REAL:
        t = _j(config.results_dir(m) / "truth_axis_meta.json")
        ia = (t.get("validity") or {}).get("instrument_agreement") or {}
        if not ia:
            continue
        L.append(f"| `{m}` | {t.get('truth_auroc_best', float('nan')):.3f} | "
                 f"{ia['sign_agreement_overall']:.3f} | {ia['t_hat_vs_truth_acc']:.3f} | "
                 f"{ia['b_hat_vs_truth_acc']:.3f} | {ia['label_disagreement_rate']:.3f} |")
    L += ["", "Agreement by |t_hat| stratum (Qwen3.5-9B) — this is why the old, "
          "`d_truth`-derived label was noise where it mattered:", ""]
    ia = ((_j(config.results_dir("qwen3.5-9b") / "truth_axis_meta.json").get("validity")
           or {}).get("instrument_agreement") or {})
    for k, v in (ia.get("by_abs_t_hat") or {}).items():
        L.append(f"- `|t_hat| {k}` — sign agreement **{v['sign_agreement']:.3f}**, "
                 f"d_truth vs ground truth {v['t_hat_vs_truth']:.3f} (n={v['n']})")
    L += ["", "Source: `results/<model>/truth_axis_meta.json` → `validity."
          "instrument_agreement`.", ""]

    # verification
    L += ["## Verification status", ""]
    for m in REAL:
        p = config.results_dir(m) / "verification.md"
        if p.exists():
            txt = p.read_text()
            ok = "MISMATCH" not in txt
            L.append(f"- `{m}`: {'all directly-comparable quantities reproduce' if ok else '**MISMATCHES PRESENT**'} "
                     f"(`results/{m}/verification.md`)")
    L += ["", "`scripts/verify.py` recomputes each number with code that imports nothing "
          "from the analysis modules.", ""]

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
